package view;

import controller.sysdata;
import model.Question;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import java.awt.Font;
import java.awt.Color;

public class DeletingQuestion extends javax.swing.JFrame {

	/**
	 * Creates new form DeletingQuestion
	 */
	public DeletingQuestion() {
		getContentPane().setBackground(new Color(204, 255, 153));
		initComponents();
		for (Question q : sysdata.getInstance().questions) {
			jComboBox1.addItem(q.getQuestion());
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel1.setFont(new Font("Tahoma", Font.PLAIN, 16));
		jComboBox1 = new javax.swing.JComboBox<>();
		jComboBox1.setBackground(new Color(153, 204, 153));
		jComboBox1.setFont(new Font("Tahoma", Font.PLAIN, 14));
		jButton1 = new javax.swing.JButton();
		jButton1.setBackground(new Color(153, 204, 153));
		jButton1.setFont(new Font("Tahoma", Font.PLAIN, 16));
		jButton1.addActionListener(new ActionListener() {

			public void actionPerformed(ActionEvent arg0) {

				String num = jComboBox1.getSelectedItem().toString();
				for (Question q : sysdata.getInstance().questions) {
					if (q.getQuestion().equals(num)) {
						sysdata.getInstance().DeleteQuestion(num);
						JOptionPane.showMessageDialog(rootPane, "Your Question have been deleted Successfully",
								"Success", JOptionPane.INFORMATION_MESSAGE);
						jComboBox1.removeAllItems();
						for (Question w : sysdata.getInstance().questions) {
							jComboBox1.addItem(w.getQuestion());
						}
						return;
					}
				}

				JOptionPane.showMessageDialog(rootPane, "Question not found", "Error", JOptionPane.ERROR_MESSAGE);
			}
		});

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Delete Question ");

		jLabel1.setText("Choose Question to delete");

		jButton1.setText("Delete");

		JButton btnNewButton = new JButton("Cancel");
		btnNewButton.setFont(new Font("Tahoma", Font.PLAIN, 16));
		btnNewButton.setBackground(new Color(153, 204, 153));
		btnNewButton.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	            	jCancelButton1ActionPerformed(evt);
	            }
	        });

		 
		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
						.addGroup(layout.createSequentialGroup()
							.addComponent(btnNewButton)
							.addGap(18)
							.addComponent(jButton1))
						.addGroup(layout.createSequentialGroup()
							.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 224, GroupLayout.PREFERRED_SIZE)
							.addGap(4)
							.addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, 484, GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(ComponentPlacement.RELATED)))
					.addContainerGap(25, Short.MAX_VALUE))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jComboBox1, GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
						.addComponent(jLabel1))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jButton1)
						.addComponent(btnNewButton))
					.addContainerGap())
		);
		getContentPane().setLayout(layout);

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(DeletingQuestion.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(DeletingQuestion.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(DeletingQuestion.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(DeletingQuestion.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new DeletingQuestion().setVisible(true);
			}
		});
	}
	private void jCancelButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        QuestionManager qm = new QuestionManager();
        qm.setVisible(true);
    }
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JComboBox<String> jComboBox1;
	private javax.swing.JLabel jLabel1;
}
