package view;

import java.util.ArrayList;
import javax.swing.JOptionPane;

import controller.importFromJson;
import controller.sysdata;
import model.Question;
import utils.E_Level;

import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import java.awt.Color;
import java.awt.SystemColor;
import javax.swing.JButton;
import java.awt.Font;

public class AddingQuestion extends javax.swing.JFrame {

	/**
	 * Creates new form AddingQuestion
	 */
	public AddingQuestion() {
		getContentPane().setBackground(new Color(204, 255, 153));
		initComponents();
		jPanel2.setVisible(false);
		jButton2.setVisible(false);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jPanel1.setBackground(new Color(204, 255, 153));
		jButton1 = new javax.swing.JButton();
		jButton1.setBackground(new Color(153, 204, 153));
		jButton1.setFont(new Font("Tahoma", Font.PLAIN, 16));
		jLabel8 = new javax.swing.JLabel();
		jLabel8.setFont(new Font("Tahoma", Font.PLAIN, 16));
		jTextFieldQuestion = new javax.swing.JTextField();
		jTextFieldQuestion.setFont(new Font("Tahoma", Font.PLAIN, 16));
		jPanel3 = new javax.swing.JPanel();
		jPanel3.setBackground(new Color(204, 255, 153));
		jTextFieldans4 = new javax.swing.JTextField();
		jTextFieldans3 = new javax.swing.JTextField();
		jTextFieldans1 = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jLabel4.setFont(new Font("Tahoma", Font.PLAIN, 16));
		jTextFieldans2 = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jLabel3.setFont(new Font("Tahoma", Font.PLAIN, 16));
		jLabel5 = new javax.swing.JLabel();
		jLabel5.setFont(new Font("Tahoma", Font.PLAIN, 16));
		jLabel2 = new javax.swing.JLabel();
		jLabel2.setFont(new Font("Tahoma", Font.PLAIN, 16));
		jPanel2 = new javax.swing.JPanel();
		jPanel2.setBackground(new Color(204, 255, 153));
		jLabel6 = new javax.swing.JLabel();
		jLabel6.setFont(new Font("Tahoma", Font.PLAIN, 16));
		correctAnswerComboBox = new javax.swing.JComboBox<>();
		correctAnswerComboBox.setFont(new Font("Tahoma", Font.PLAIN, 16));
		correctAnswerComboBox.setBackground(new Color(204, 255, 153));
		jLabel7 = new javax.swing.JLabel();
		jLabel7.setFont(new Font("Tahoma", Font.PLAIN, 16));
		levelComboBox = new javax.swing.JComboBox<>();
		levelComboBox.setFont(new Font("Tahoma", Font.PLAIN, 16));
		levelComboBox.setBackground(new Color(204, 255, 153));
		jButton2 = new javax.swing.JButton();
		jButton2.setBackground(new Color(153, 204, 153));
		jButton2.setFont(new Font("Tahoma", Font.PLAIN, 16));
		jButton2.setForeground(new Color(0, 0, 0));

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Adding Question");

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Rabbit Team"));

		jButton1.setText("Continue");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jLabel8.setText("Question");

		jLabel4.setText("Answer 3");

		jLabel3.setText("Answer 2");

		jLabel5.setText("Answer 4");

		jLabel2.setText("Answer 1");

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3Layout.setHorizontalGroup(
			jPanel3Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel3Layout.createSequentialGroup()
							.addComponent(jLabel5)
							.addGap(18)
							.addComponent(jTextFieldans4, GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE))
						.addGroup(jPanel3Layout.createParallelGroup(Alignment.TRAILING, false)
							.addGroup(jPanel3Layout.createSequentialGroup()
								.addComponent(jLabel4)
								.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jTextFieldans3, GroupLayout.PREFERRED_SIZE, 334, GroupLayout.PREFERRED_SIZE))
							.addGroup(jPanel3Layout.createSequentialGroup()
								.addComponent(jLabel2)
								.addGap(18)
								.addComponent(jTextFieldans1, GroupLayout.PREFERRED_SIZE, 334, GroupLayout.PREFERRED_SIZE)))
						.addGroup(jPanel3Layout.createSequentialGroup()
							.addComponent(jLabel3)
							.addGap(18)
							.addComponent(jTextFieldans2)))
					.addGap(22))
		);
		jPanel3Layout.setVerticalGroup(
			jPanel3Layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(jPanel3Layout.createSequentialGroup()
					.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jTextFieldans1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel2))
					.addGap(18)
					.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jTextFieldans2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel3))
					.addGap(18)
					.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jTextFieldans3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel4))
					.addGap(18)
					.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jTextFieldans4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel5))
					.addGap(52))
		);
		jPanel3.setLayout(jPanel3Layout);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1Layout.setHorizontalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addComponent(jLabel8)
							.addPreferredGap(ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
							.addComponent(jTextFieldQuestion, GroupLayout.PREFERRED_SIZE, 482, GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addGap(0, 489, Short.MAX_VALUE)
							.addComponent(jButton1))
						.addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, 441, GroupLayout.PREFERRED_SIZE))
					.addContainerGap())
		);
		jPanel1Layout.setVerticalGroup(
			jPanel1Layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
						.addGroup(Alignment.LEADING, jPanel1Layout.createSequentialGroup()
							.addGap(28)
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jLabel8)
								.addComponent(jTextFieldQuestion, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
							.addGap(35)
							.addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, 162, GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addGap(0, 235, Short.MAX_VALUE)
							.addComponent(jButton1)))
					.addContainerGap())
		);
		jPanel1.setLayout(jPanel1Layout);

		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Rabbit Team"));

		jLabel6.setText("Choose the correct answer");

		jLabel7.setText("Level");

		levelComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2Layout.setHorizontalGroup(
			jPanel2Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING, false)
						.addComponent(jLabel7, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jLabel6, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
					.addGap(18)
					.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING, false)
						.addComponent(levelComboBox, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(correctAnswerComboBox, 0, 271, Short.MAX_VALUE))
					.addGap(155))
		);
		jPanel2Layout.setVerticalGroup(
			jPanel2Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(correctAnswerComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel6))
					.addGap(18)
					.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jLabel7)
						.addComponent(levelComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addContainerGap(38, Short.MAX_VALUE))
		);
		jPanel2.setLayout(jPanel2Layout);

		jButton2.setText("Add Question");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		JButton btnCancel = new JButton("Cancel");
		btnCancel.setBackground(new Color(153, 204, 153));
		btnCancel.setFont(new Font("Tahoma", Font.PLAIN, 16));

		btnCancel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCancelButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
						.addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
						.addGroup(layout.createSequentialGroup()
							.addComponent(btnCancel, GroupLayout.PREFERRED_SIZE, 113, GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(ComponentPlacement.RELATED, 349, Short.MAX_VALUE)
							.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 134, GroupLayout.PREFERRED_SIZE))
						.addComponent(jPanel1, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE))
					.addContainerGap())
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addContainerGap()
					.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					.addGap(18)
					.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					.addGap(18)
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jButton2)
						.addComponent(btnCancel))
					.addContainerGap(33, Short.MAX_VALUE))
		);
		getContentPane().setLayout(layout);

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		correctAnswerComboBox.removeAllItems();
		correctAnswerComboBox.addItem(jTextFieldans1.getText());
		correctAnswerComboBox.addItem(jTextFieldans2.getText());
		correctAnswerComboBox.addItem(jTextFieldans3.getText());
		correctAnswerComboBox.addItem(jTextFieldans4.getText());
		jPanel2.setVisible(true);
		jButton2.setVisible(true);
	}// GEN-LAST:event_jButton1ActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		// sysdata s = sysdata.getInstance();
		ArrayList<String> ta = new ArrayList<>();
		ta.add(jTextFieldans1.getText());
		ta.add(jTextFieldans2.getText());
		ta.add(jTextFieldans3.getText());
		ta.add(jTextFieldans4.getText());
		System.out.println(jTextFieldQuestion.getText());

		if (importFromJson.Addquestiontojson(jTextFieldQuestion.getText(), ta, correctAnswerComboBox.getSelectedIndex(),
				levelComboBox.getSelectedIndex() + 1)) {
			JOptionPane.showMessageDialog(rootPane, "Your Question have been Added Successfully", "Success",
					JOptionPane.INFORMATION_MESSAGE);
			this.setVisible(false);
			QuestionManager qm = new QuestionManager();
			qm.setVisible(true);
		} else {
			JOptionPane.showMessageDialog(rootPane, "wrong details try again ", "Error", JOptionPane.ERROR_MESSAGE);

		}

	}// GEN-LAST:event_jButton2ActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(AddingQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(AddingQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(AddingQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(AddingQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AddingQuestion().setVisible(true);
			}
		});
	}

	private void jCancelButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		this.setVisible(false);
		QuestionManager qm = new QuestionManager();
		qm.setVisible(true);
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JComboBox<String> correctAnswerComboBox;
	private javax.swing.JComboBox<String> levelComboBox;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JTextField jTextFieldQuestion;
	private javax.swing.JTextField jTextFieldans1;
	private javax.swing.JTextField jTextFieldans2;
	private javax.swing.JTextField jTextFieldans3;
	private javax.swing.JTextField jTextFieldans4;
}
