package view;
import java.awt.Font;
import java.util.HashSet;
import java.util.Set;

import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

import controller.sysdata;
import model.Player;

public class History extends javax.swing.JFrame {
	private JTable table;

    /**
     * Creates new form History
     */
    public History(Player p) {
//    	if(p==null) {
//    		p=sysdata.getInstance().players.iterator().next();
//    	}
        initComponents(p);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(Player p ) {
    
      
			
		
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        

       
     
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
    	String[] columnNames= new String[3];
		Object[][] arrayOFlist = null;
		 columnNames[0] = "Playe ID";
	      columnNames[1]=  "player Name ";
	      columnNames[2]= "player score";
	      int i = 0;
			
			 Set<Player> PlayerSet=null;
			try{
				PlayerSet=sysdata.getInstance().players;
				
			
				
			 
			 }
			
			catch(NullPointerException n){
				PlayerSet = new  HashSet<Player>();
			}
			
			arrayOFlist = new Object[PlayerSet.size() * 100][3];
			if(p!=null) {
			for (Player les : PlayerSet) {
				
			if( p.ID == les.getID()) {
				arrayOFlist[i][0] = les.ID;
				arrayOFlist[i][1] = les.name;
				arrayOFlist[i][2] = les.highscore;
				i++;
			}
			}
			}else {
				for (Player les : PlayerSet) {
					
					
						arrayOFlist[i][0] = les.ID;
						arrayOFlist[i][1] = les.name;
						arrayOFlist[i][2] = les.highscore;
						i++;
					}
					
			}
			
		
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    //    getContentPane().setLayout(null);
        
        JScrollPane scrollPane = new JScrollPane();
        scrollPane.setBounds(0, 45, 437, 313);
       
        
        table = new JTable(arrayOFlist, columnNames);
		scrollPane = new JScrollPane(table);
		scrollPane.setBounds(0, 45, 596, 378);
		
		getContentPane().add(scrollPane);
       JLabel j = new JLabel("History Of The High Score ");
       j.setBounds(100, 10, 500, 22);
       j.setFont(new Font("Serif", Font.PLAIN, 16));
       getContentPane().add(j);
        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new History(null).setVisible(true);
            }
        });
    }
}
